
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naseem 
 */
public class loginf extends javax.swing.JFrame {

    /**
     * Creates new form loginf
     */
  String name;
  String M;
  Connection conn=null;
  Statement stmt=null;
  ResultSet rs=null;

    public loginf() {
        initComponents();
        conn=databaseConnection.connection();
        
        setBackground(new Color (255,255,255,0));
        this.setLocationRelativeTo(null);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        k1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        admin_email = new javax.swing.JTextField();
        admin_pass = new javax.swing.JTextField();
        Email_Logo2 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        Email_Logo3 = new javax.swing.JLabel();
        kButton3 = new keeptoo.KButton();
        cs = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        kButton1.setText("kButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(355, 450));
        setUndecorated(true);

        k1.setBackground(new java.awt.Color(255, 255, 255,0));
        k1.setBorder(null);
        k1.setkBorderRadius(80);
        k1.setkEndColor(new java.awt.Color(0, 0, 0));
        k1.setkGradientFocus(50);
        k1.setkStartColor(new java.awt.Color(153, 50, 204,245));
        k1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                k1MouseDragged(evt);
            }
        });
        k1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                k1MousePressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_male_user_70px_1_1.png"))); // NOI18N

        admin_email.setBackground(new java.awt.Color(255, 255, 255,0));
        admin_email.setForeground(new java.awt.Color(204, 204, 204));
        admin_email.setText("E-Mail");
        admin_email.setBorder(null);
        admin_email.setSelectionColor(new java.awt.Color(204, 0, 204));
        admin_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_emailFocusLost(evt);
            }
        });

        admin_pass.setBackground(new java.awt.Color(255, 255, 255,0));
        admin_pass.setForeground(new java.awt.Color(204, 204, 204));
        admin_pass.setText("Password");
        admin_pass.setBorder(null);
        admin_pass.setSelectionColor(new java.awt.Color(204, 0, 204));
        admin_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_passFocusLost(evt);
            }
        });
        admin_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                admin_passKeyPressed(evt);
            }
        });

        Email_Logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email_Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_padlock_20px.png"))); // NOI18N

        jSeparator15.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator16.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator16.setForeground(new java.awt.Color(204, 204, 204));

        Email_Logo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email_Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_envelope_20px.png"))); // NOI18N

        kButton3.setBackground(new java.awt.Color(255, 255, 255,0));
        kButton3.setText("Sign In");
        kButton3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        kButton3.setkBorderRadius(40);
        kButton3.setkEndColor(new java.awt.Color(255, 102, 255));
        kButton3.setkHoverColor(new java.awt.Color(255, 0, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(153, 0, 153));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(75, 0, 130));
        kButton3.setkIndicatorColor(new java.awt.Color(75, 0, 130));
        kButton3.setkIndicatorThickness(1);
        kButton3.setkPressedColor(new java.awt.Color(75, 0, 130));
        kButton3.setkStartColor(new java.awt.Color(75, 0, 130));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        cs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_filled_circle_15px_1.png"))); // NOI18N
        cs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                csMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                csMouseExited(evt);
            }
        });

        javax.swing.GroupLayout k1Layout = new javax.swing.GroupLayout(k1);
        k1.setLayout(k1Layout);
        k1Layout.setHorizontalGroup(
            k1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(k1Layout.createSequentialGroup()
                .addGroup(k1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(k1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(k1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(k1Layout.createSequentialGroup()
                                .addComponent(Email_Logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(k1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(admin_email, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, k1Layout.createSequentialGroup()
                                .addComponent(Email_Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(admin_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(k1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, k1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cs)
                .addGap(36, 36, 36))
        );
        k1Layout.setVerticalGroup(
            k1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(k1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addGroup(k1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(k1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(k1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(k1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_emailFocusGained
        admin_email.setText("");
    }//GEN-LAST:event_admin_emailFocusGained

    private void admin_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_emailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_emailFocusLost

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
    try{
    stmt=conn.createStatement();
    String admin_mail=admin_email.getText();
    String admin_pas=admin_pass.getText();
  boolean check=false;
 
    
    
    String sql="SELECT * FROM `admin`";
    rs=stmt.executeQuery(sql);
    L1:while(rs.next()){
  
        String mail =rs.getString(2);
        String pass=rs.getString(3);
       String n=rs.getString(4);
     
      int i=string(mail,admin_mail);
   if(i==1)
   {
             
            int j=string(pass,admin_pas);
                                  if(j==1)
                                  {
                                      System.out.println("Valid");
                                      check=true;
                                      name=noSpace(n);
                                      M=noSpace(mail);
                                      
                                      System.out.println(name+" "+M);
                                      
                                      break L1;
                                      
                                  }
   }
    
        
    }
    
    if(check==true){
    setVisible(false);
   Home obj=new Home(name,M);   
    obj.setVisible(true);
    }
    else{  
          ImageIcon icon =new ImageIcon(getClass().getResource("/icons8_denied_50px_1.png"));
      JOptionPane.showMessageDialog(null,"Mail or Password Invalid","",JOptionPane.PLAIN_MESSAGE,icon);
    }
    
    
    }catch(Exception e){
     
      JOptionPane.showMessageDialog(null, e);
    }
        
    }//GEN-LAST:event_kButton3ActionPerformed


    
    
    public int  string(String mail,String admin_mail){
       char[] array=mail.toCharArray();
       char[] array2=admin_mail.toCharArray();
        char[] newmail=new char[admin_mail.length()];
         boolean check=false;
         int a=0;
        int b=array2.length;
        
         for(int i=0;i<array.length;i++){
        if(array[i] !=' '){
        a++;
        }
        }
    
        
         if(a==b){
        
         
        for(int i=0,j=0;i<array.length;i++)       
        {
    
                   if(array[i]!=' ')
                   {
                       newmail[j]=array[i];
                       
                       if(j<newmail.length)
                       {
                         j++;
                       }
                   
                   }           
         }  
        
        
        
         }
        /*for(int i=0;i<array2.length;i++){
        System.out.print(array2[i]);
        }*/
       
                   for(int  i=0;i<array2.length;i++){
                   if(newmail[i] != array2[i]){
                       check=false;
                       break;
                   }
                   check=true ;
                   }
                   
                   
                   if(check==true){
                  //System.out.println("match");
                  return 1;
                   }else{
                  // System.out.println("not match");
                     return 0;
                   }
    
        
  
      
    
    
    }
    
    
    
    
    
    public String noSpace(String a){
          char[] array=a.toCharArray();
          int c=0;
           for(int i=0;i<array.length;i++){
        if(array[i] !=' '){
            if(c<array.length){
        c++;
            }
        }
        }
         
          char[] newArray=new char[c];
          
           for(int i=0,j=0;i<array.length;i++)       
        {
    
                   if(array[i]!=' ')
                   {
                       newArray[j]=array[i];
                       
                       if(j<newArray.length)
                       {
                         j++;
                       }
                   
                   }           
         }  
          String r=String.valueOf(newArray);
      return r;
    
    
    
    
    }
    private void k1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_k1MousePressed
        MouseX=evt.getX();
        MouseY=evt.getY();
    }//GEN-LAST:event_k1MousePressed

    private void k1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_k1MouseDragged
   int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-MouseX,y-MouseY);
    }//GEN-LAST:event_k1MouseDragged

    private void admin_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_passFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_passFocusLost

    private void admin_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_passFocusGained
        admin_pass.setText("");
    }//GEN-LAST:event_admin_passFocusGained

    private void csMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseEntered
          cs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_filled_circle_15px_1.png")));
    }//GEN-LAST:event_csMouseEntered

    private void csMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseExited
       cs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_filled_circle_15px.png")));
    }//GEN-LAST:event_csMouseExited

    private void csMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseClicked
       System.exit(0);
    }//GEN-LAST:event_csMouseClicked

    private void admin_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_passKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           try{
    stmt=conn.createStatement();
    String admin_mail=admin_email.getText();
    String admin_pas=admin_pass.getText();
  boolean check=false;
 
    
    
    String sql="SELECT * FROM `admin`";
    rs=stmt.executeQuery(sql);
    L1:while(rs.next()){
  
        String mail =rs.getString(2);
        String pass=rs.getString(3);
       String n=rs.getString(4);
     
      int i=string(mail,admin_mail);
   if(i==1)
   {
             
            int j=string(pass,admin_pas);
                                  if(j==1)
                                  {
                                      System.out.println("Valid");
                                      check=true;
                                      name=noSpace(n);
                                      M=noSpace(mail);
                                      
                                      System.out.println(name+" "+M);
                                      
                                      break L1;
                                      
                                  }
   }
    
        
    }
    
    if(check==true){
    setVisible(false);
   Home obj=new Home(name,M);   
    obj.setVisible(true);
    }
    else{  
          ImageIcon icon =new ImageIcon(getClass().getResource("/icons8_denied_50px_1.png"));
      JOptionPane.showMessageDialog(null,"Mail or Password Invalid","",JOptionPane.PLAIN_MESSAGE,icon);
    }
    
    
    }catch(Exception e){
     
      JOptionPane.showMessageDialog(null, e);
    }
        
      }
    }//GEN-LAST:event_admin_passKeyPressed
  int MouseX,MouseY;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email_Logo2;
    private javax.swing.JLabel Email_Logo3;
    private javax.swing.JTextField admin_email;
    private javax.swing.JTextField admin_pass;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private keeptoo.KGradientPanel k1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton3;
    // End of variables declaration//GEN-END:variables

    private void session(String name, String mail) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
